services:
  frontend:
    build: ./frontend
    container_name: svelte_app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5555:5173"

  backend:
    build: ./backend
    container_name: laravel_app
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"